-- CREACIÓN DE TABLAS TEMPORALES 
-- Las tablas temporales se crean de la misma forma que las tablas persistentes. Se almacenan en la BD TEMPDB. 
-- Se eliminan cuando la conexión de sesión se cierra. 

use PEDIDOS
go 

SELECT * FROM PRODUCTOS 
SELECT * FROM DETALLE_ORDENES 

CREATE TABLE #VENTAS_PRODUCTO ( PRODUCTOID INT PRIMARY KEY, TOTALVTA INT )
INSERT INTO #VENTAS_PRODUCTO
 SELECT PRODUCTOID, SUM(CANTIDAD)
 FROM DETALLE_ORDENES 
 GROUP BY PRODUCTOID

 SELECT DESCRIPCION, TOTALVTA 
 FROM #VENTAS_PRODUCTO VP JOIN PRODUCTOS P
 ON VP.PRODUCTOID = P.PRODUCTOID
 ORDER BY DESCRIPCION 


 -- USO DE LA SENTENCIA TOP

SELECT TOP number|percent column_name(s)
FROM table_name
WHERE condition;

SELECT TOP 3 * FROM PRODUCTOS

SELECT TOP 5 PERCENT * FROM PRODUCTOS 

SELECT TOP 1 PRODUCTOID FROM #VENTAS_PRODUCTO



