-- Drop all tables and their indexes, constraints, and triggers.
DROP TABLE ORDER_DETAILS PURGE;
DROP TABLE ORDERS PURGE;
DROP TABLE PRODUCTS PURGE;
DROP TABLE SUPPLIERS PURGE;
DROP TABLE CATEGORIES PURGE;
DROP TABLE CUSTOMERS PURGE;
DROP TABLE EMPLOYEES PURGE;
DROP TABLE SHIPPERS PURGE;

-- Drop all sequences.
DROP SEQUENCE SEQ_NW_CATEGORIES;
DROP SEQUENCE SEQ_NW_CUSTOMERS;
DROP SEQUENCE SEQ_NW_EMPLOYEES;
DROP SEQUENCE SEQ_NW_ORDERS;
DROP SEQUENCE SEQ_NW_PRODUCTS;
DROP SEQUENCE SEQ_NW_SHIPPERS;
DROP SEQUENCE SEQ_NW_SUPPLIERS;