---- 5----
    ALTER TABLE ORDERS
    DROP CONSTRAINT FK_EMPLOYEE_ID ;
    
    ALTER TABLE ORDERS
    ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE;
 ---6-- 

    ALTER TABLE ORDERS
    DROP CONSTRAINT FK_SHIPPER_ID ;
    
    ALTER TABLE ORDERS
    ADD  CONSTRAINT FK_SHIPPER_ID FOREIGN KEY (SHIP_VIA) REFERENCES SHIPPERS(SHIPPER_ID) ON DELETE CASCADE;
---7---   
ALTER TABLE ORDER_DETAILS
    DROP CONSTRAINT FK_ORDER_ID ;
    
    ALTER TABLE ORDER_DETAILS
    ADD  CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE;
---8----    
ALTER TABLE ORDER_DETAILS
    DROP CONSTRAINT FK_PRODUCT_ID ;
    
    ALTER TABLE ORDER_DETAILS
    ADD  CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID) ON DELETE CASCADE;


    